#General

SINGULARITY: "docker://mneacs/treponema-assembly:latest"
THREADS: 16     # max. number of threads per sample

#De novo assembly 

MIN_DEPTH: 5

#Scaffolding

REFERENCE: "reference/NC_021490.fasta"
RECIPE: "ragout.rcp"